let current=null, activeSheet='CTS', searchCache={};
const sheets=['CTS','MSP','ZIP','Plan','Spiel','Policies','Process','Updates','Others'];
const labels={CTS:'CTS',MSP:'MSP',ZIP:'ZIP',Plan:'PLAN',Spiel:'SPIEL',Policies:'POLICIES',Process:'PROCESS',Updates:'UPDATES',Others:'OTHERS'};
const $=id=>document.getElementById(id);
function toast(m){$('toast').textContent=m;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2500)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function login(e){e.preventDefault();const u=$('loginUser').value.trim(),p=$('loginPass').value;const hash=await sha256(p);const user=DB.users.find(x=>x.username.toLowerCase()===u.toLowerCase()&&x.passwordHash===hash);if(!user){$('loginMsg').textContent='Invalid username or password.';return}current={...user};sessionStorage.setItem('processHubCurrent',JSON.stringify(current));startApp()}
function startApp(){$('loginView').classList.add('hidden');$('app').classList.remove('hidden');$('userBadge').textContent=`${current.name} • ${current.role}`;$('manageNav').style.display=['Admin','Semi'].includes(current.role)?'block':'none';$('manageTile').style.display=['Admin','Semi'].includes(current.role)?'block':'none';loadQuick();go('dashboard');renderProfile();refreshHistory()}
function logout(){sessionStorage.removeItem('processHubCurrent');current=null;$('app').classList.add('hidden');$('loginView').classList.remove('hidden');$('loginPass').value=''}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-'+page).classList.remove('hidden');document.querySelectorAll('#nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));if(page==='search')setupSearch();if(page==='history')refreshHistory();if(page==='manage')renderUsers();if(page==='profile')renderProfile();if(page==='backup'){}if(innerWidth<801)$('sidebar').classList.remove('open')}
async function loadQuick(){const box=$('processQuick');box.innerHTML=sheets.map(s=>`<button class="tile" onclick="go('search');selectSheet('${s}')"><strong>${s==='Policies'?'⚖':'⌕'}</strong><h3>${labels[s]}</h3><p>Open ${labels[s]} reference search.</p></button>`).join('')}
async function getSheet(name){if(searchCache[name])return searchCache[name];searchCache[name]=await fetch('data/'+name+'.json').then(r=>r.json());return searchCache[name]}
function setupSearch(){if(!$('searchTabs').children.length){$('searchTabs').innerHTML=sheets.map(s=>`<button data-sheet="${s}" onclick="selectSheet('${s}')">${labels[s]}</button>`).join('')}selectSheet(activeSheet)}
async function selectSheet(s){activeSheet=s;document.querySelectorAll('#searchTabs button').forEach(b=>b.classList.toggle('active',b.dataset.sheet===s));const data=await getSheet(s);const cols=data[0]?Object.keys(data[0]):[];$('searchColumn').innerHTML='<option value="all">All columns</option>'+cols.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join('');runSearch()}
async function runSearch(){const data=await getSheet(activeSheet);const q=$('searchInput').value.trim().toLowerCase();const col=$('searchColumn').value;let rows=data;if(q)rows=data.filter(r=>{const vals=col==='all'?Object.values(r):[r[col]];return vals.some(v=>String(v??'').toLowerCase().includes(q))});$('searchCount').textContent=`${rows.length.toLocaleString()} result(s)`;const limit=rows.slice(0,250);$('searchResults').innerHTML=limit.map((r,i)=>`<div class="result"><div class="result-title">${labels[activeSheet]} #${i+1}</div><div class="result-grid">${Object.entries(r).map(([k,v])=>`<div><b>${escapeHtml(k)}:</b> ${escapeHtml(v)}</div>`).join('')}</div></div>`).join('')+(rows.length>250?'<div class="muted">Showing first 250 results. Refine your search.</div>':'')}
function renderUsers(){if(!['Admin','Semi'].includes(current.role)){go('dashboard');return}const q=($('userSearch').value||'').toLowerCase();const rows=DB.users.filter(u=>Object.values(u).join(' ').toLowerCase().includes(q));$('userTable').innerHTML=`<table><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Level</th><th>Superior</th><th>Action</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${escapeHtml(u.username)}</td><td>${escapeHtml(u.name)}</td><td>${escapeHtml(u.role)}</td><td>${escapeHtml(u.level)}</td><td>${escapeHtml(u.superior)}</td><td><button class="edit" onclick="editUser('${encodeURIComponent(u.username)}')">Edit</button><button class="del" onclick="deleteUser('${encodeURIComponent(u.username)}')">Delete</button></td></tr>`).join('')}</tbody></table>`}
function editUser(enc){const u=DB.users.find(x=>x.username===decodeURIComponent(enc));if(!u)return;$('oldUsername').value=u.username;$('newUsername').value=u.username;$('newPassword').value='';$('newName').value=u.name;$('newRole').value=u.role;$('newLevel').value=u.level;$('newSuperior').value=u.superior;go('manage')}
function deleteUser(enc){if(current.role!=='Admin')return toast('Only Admin can delete users.');const name=decodeURIComponent(enc);if(name===current.username)return toast('You cannot delete your own account.');if(!confirm('Delete '+name+'?'))return;DB.users=DB.users.filter(u=>u.username!==name);saveDB();renderUsers();toast('User deleted.')}
$('userForm').addEventListener('submit',async e=>{e.preventDefault();if(!['Admin','Semi'].includes(current.role))return;const old=$('oldUsername').value.trim(),username=$('newUsername').value.trim(),pass=$('newPassword').value,name=$('newName').value.trim(),role=$('newRole').value,level=$('newLevel').value.trim(),superior=$('newSuperior').value.trim();if(!username||!name)return;const duplicate=DB.users.some(u=>u.username.toLowerCase()===username.toLowerCase()&&u.username!==old);if(duplicate)return toast('Username already exists.');if(old){const u=DB.users.find(x=>x.username===old);u.username=username;u.name=name;u.role=role;u.level=level;u.superior=superior;if(pass)u.passwordHash=await sha256(pass)}else{if(!pass)return toast('Password is required for a new user.');DB.users.push({username,passwordHash:await sha256(pass),role,name,level,superior})}saveDB();$('userForm').reset();$('oldUsername').value='';renderUsers();toast('User saved.')});
$('resetUser').onclick=()=>{$('userForm').reset();$('oldUsername').value=''};$('userSearch').oninput=renderUsers;
function renderProfile(){$('profileName').value=current.name;$('profileRole').value=current.role;$('profileLevel').value=current.level;$('profileUsername').value=current.username}
$('profileSave').onclick=async()=>{const nu=$('profileUsername').value.trim(),np=$('profilePassword').value;const u=DB.users.find(x=>x.username===current.username);if(!u)return;if(nu!==current.username&&DB.users.some(x=>x.username.toLowerCase()===nu.toLowerCase()))return toast('Username already exists.');u.username=nu;if(np)u.passwordHash=await sha256(np);current={...u};sessionStorage.setItem('processHubCurrent',JSON.stringify(current));$('userBadge').textContent=`${current.name} • ${current.role}`;toast('Profile updated.')};
function historyCanView(row){const role=current.role;if(role==='Admin')return true;const sup=String(row.Superior||row['Column 5']||'').trim().toLowerCase();const user=String(row.User||row['Column 2']||'').trim().toLowerCase();if(role==='Semi')return user===current.name.toLowerCase()||sup===current.name.toLowerCase()||(!sup&&row.Level===current.level);return user===current.name.toLowerCase()}
function refreshHistory(){if(!current)return;const q=($('historySearch').value||'').toLowerCase();let rows=localHistory().filter(historyCanView).filter(r=>Object.values(r).join(' ').toLowerCase().includes(q));$('historyResults').innerHTML=rows.slice().reverse().map((r,i)=>`<div class="history-item"><div class="history-head" onclick="this.nextElementSibling.style.display=this.nextElementSibling.style.display==='block'?'none':'block'"><b>${escapeHtml(String(r.User||'Calculation'))}</b><span>${escapeHtml(String(r.Timestamp||''))}</span></div><div class="history-body"><pre>${escapeHtml(r['Result Output']||'')}</pre><button class="primary" onclick="navigator.clipboard.writeText(this.previousElementSibling.textContent);toast('Copied')">Copy</button></div></div>`).join('')||'<p class="muted">No records found.</p>'}
$('historySearch').oninput=refreshHistory;$('clearLocalHistory').onclick=()=>{if(!confirm('Clear locally created calculation records? Imported records will also be reset after reload.'))return;DB.history=DB.history.filter(x=>!x._local);saveDB();refreshHistory()}
function calcShell(kind){const title={standard:'Standard Rebate',monthly:'Monthly Rebate',checker:'Rebate Checker'}[kind];$('calculatorBox').innerHTML=`<div class="card calc"><div class="page-head"><h3>${title}</h3><button class="secondary" onclick="$('calculatorBox').innerHTML=''">Close</button></div><div class="calc-form"><label>Plan Amount<input id="cPlan" type="number" step="0.01"></label><label>Account Number<input id="cAcc"></label><label>Reference<input id="cRef"></label><label>Billing Cycle<select id="cCycle"><option value="A">A - 1st</option><option value="B">B - 8th</option><option value="C">C - 15th</option><option value="D">D - 22nd</option><option value="E">E - Manual Monthly</option><option value="Quarterly">Quarterly</option><option value="Semi">Semi-Annual</option><option value="Annual">Annual</option></select></label><label>Rebate Type<select id="cFactor"><option value="1">No Connection (100%)</option><option value="0.3">Slow / Intermittent (30%)</option></select></label><label>CRM<select id="cCrm"><option>IBAS</option><option>ICMS</option></select></label><label>RFO<input id="cRfo"></label><label>Manual Anchor<input id="cAnchor" type="date"></label><div class="ranges"><b>Affected periods</b><div id="rangeBox"></div><button class="secondary" type="button" onclick="addRange()">+ Add period</button></div></div><div style="margin-top:12px"><button class="primary" onclick="calculate('${kind}')">Calculate</button><button class="secondary" onclick="copyCalc()">Copy</button></div><div id="calcOutput" class="output"></div></div>`;addRange()}
function addRange(){const box=$('rangeBox');const d=document.createElement('div');d.className='range';d.innerHTML='<input type="date" class="start"><input type="date" class="restore"><button class="danger" type="button">×</button>';d.lastElementChild.onclick=()=>d.remove();box.appendChild(d)}
function cfgFor(key){return {A:{d:1,m:1,f:1},B:{d:8,m:1,f:1},C:{d:15,m:1,f:1},D:{d:22,m:1,f:1},E:{manual:true,m:1,f:1},Quarterly:{manual:true,m:3,f:2.75},Semi:{manual:true,m:6,f:5.5},Annual:{manual:true,m:12,f:11}}[key]}
function localDate(s){const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}
function fmt(d){return d.toLocaleDateString('en-US',{month:'short',day:'2-digit',year:'numeric'}).toUpperCase()}
function calculate(kind){const plan=parseFloat($('cPlan').value),acc=$('cAcc').value.trim(),ref=$('cRef').value.trim(),key=$('cCycle').value,factor=parseFloat($('cFactor').value),crm=$('cCrm').value,rfo=$('cRfo').value,cfg=cfgFor(key);if(!plan||!acc||!ref)return toast('Fill in Plan, Account and Reference.');const ranges=[...document.querySelectorAll('#rangeBox .range')].map(x=>({s:x.querySelector('.start').value,r:x.querySelector('.restore').value})).filter(x=>x.s&&x.r);if(!ranges.length)return toast('Enter at least one affected period.');let total=0,days=0,lines=[];for(const rg of ranges){let cur=localDate(rg.s),stop=new Date(localDate(rg.r)-86400000);while(cur<=stop){let bs;if(cfg.manual){const a=$('cAnchor').value;if(!a)return toast('Manual Anchor is required.');bs=localDate(a);while(new Date(bs.getFullYear(),bs.getMonth()+cfg.m,bs.getDate())<=cur)bs.setMonth(bs.getMonth()+cfg.m);while(cur<bs)bs.setMonth(bs.getMonth()-cfg.m)}else{bs=new Date(cur.getFullYear(),cur.getMonth(),cfg.d);if(cur.getDate()<cfg.d)bs.setMonth(bs.getMonth()-1)}let be=new Date(bs.getFullYear(),bs.getMonth()+cfg.m,bs.getDate()-1),as=cur>bs?cur:bs,ae=stop<be?stop:be,d=Math.floor((Date.UTC(ae.getFullYear(),ae.getMonth(),ae.getDate())-Date.UTC(as.getFullYear(),as.getMonth(),as.getDate()))/86400000)+1,pd=Math.floor((Date.UTC(be.getFullYear(),be.getMonth(),be.getDate())-Date.UTC(bs.getFullYear(),bs.getMonth(),bs.getDate()))/86400000)+1,amt=(plan*cfg.f/pd)*d*factor;if(crm==='ICMS')amt/=1.12;total+=amt;days+=d;lines.push(`FORMULA: ${fmt(as)} - ${fmt(ae)}: (${plan} × ${cfg.f} / ${pd}) × ${d}${crm==='ICMS'?' / 1.12':''}${factor===0.3?' × 0.3':''} = ${amt.toFixed(4)}`);cur=new Date(be.getTime()+86400000)}}let out=`PREPARED BY: ${current.name}\nACCOUNT NUMBER: ${acc}\nREFERENCE: ${ref}\nBILLING CYCLE: ${key}\nCRM: ${crm}\nPLAN: ${plan.toFixed(2)}\nTOTAL REQUESTED DAYS: ${days}\n\nBREAKDOWN:\n${lines.join('\n')}\n\nESTIMATED REBATE AMOUNT: ${total.toFixed(2)}\nRFO: ${rfo}`;$('calcOutput').textContent=out;if(kind!=='checker'){addHistory(out,current.name,current.level,current.superior);toast('Calculation saved locally.')}else toast('Calculation complete.')}
function copyCalc(){navigator.clipboard.writeText($('calcOutput').textContent).then(()=>toast('Copied'))}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));document.querySelectorAll('[data-calc]').forEach(b=>b.addEventListener('click',()=>calcShell(b.dataset.calc)));$('loginForm').addEventListener('submit',login);$('logoutBtn').onclick=logout;$('searchBtn').onclick=runSearch;$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('ph_theme',document.body.classList.contains('dark')?'dark':'light')};$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('exportBtn').onclick=exportDB;$('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj.users||!obj.history)throw Error();DB=obj;saveDB();toast('Imported. Reloading...');setTimeout(()=>location.reload(),700)}catch(_){toast('Invalid backup file.')}};$('resetData').onclick=async()=>{if(!confirm('Reset local changes and restore the imported seed data?'))return;localStorage.removeItem(DB_KEY);location.reload()};
setInterval(()=>$('clock').textContent=new Date().toLocaleString(),1000);if(localStorage.getItem('ph_theme')==='dark')document.body.classList.add('dark');(async()=>{await initDB();const s=sessionStorage.getItem('processHubCurrent');if(s){current=JSON.parse(s);startApp()}})();
